### ISSUE TITLE
Why has there been no new versions of the layer since January?

### ISSUE THREAD

**Issue by mrBoie** [DataDog/dd-trace-dotnet-aws-lambda-layer#5]
Hello, 

Is this layer still supported?

The underlying package has been upgraded to 2.57 whilst the layer 15 which is the latest layer is still stuck on 2.46.
Is there some reason behind this?

**Comment by duncanista** [comment]
Hey @mrBoie,

Sorry for the delayed response.
Yes, this is still supported, sorry for not releasing lately. We'll do a release soon, which should improve cold starts greatly. I'll keep updating!

**Comment by mrBoie** [comment]
Hi,

Nice to hear! 👍

**Comment by duncanista** [comment]
Should have a release early next week!

The improvement is going to reduce the overhead around `300ms` as per my tests! 😸

**Comment by mrBoie** [comment]
Awesome, looking forward to it 🥳

**Comment by duncanista** [comment]
Hey @mrBoie,

Yeah! We are also working on improving our Datadog Lambda Extension overhead, right now the Optimized version is in beta for Python and NodeJS, I'm currently working on allowing support for other runtimes such as .NET, Java, Go and Ruby. This should lower the cold start for .NET below a second!

Will keep you updated!

**Comment by duncanista** [comment]
Please find the latest release available[ v16](https://github.com/DataDog/dd-trace-dotnet-aws-lambda-layer/releases/tag/v16) which should have the tracer version [v2.59.0](https://github.com/DataDog/dd-trace-dotnet/releases/tag/v2.59.0).

This version should have a 300ms improvement in cold starts.

Feel free to reopen if there's any issues.
